# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: 'tools/schemacode/bidsschematools/tests/data/broken_dataset_description.json'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: check-added-large-files
      - id: check-case-conflict
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        files: ^tools/(?!schemacode)
        args: ["--verbose"]
      - id: black
        name: "black bidsschematools"
        files: tools/schemacode
        args: ["--config", "tools/schemacode/pyproject.toml", "--verbose"]
  - repo: https://github.com/pyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^tools/(?!schemacode)
        args: ["--profile", "black"]
      - id: isort
        name: "isort bidsschematools"
        files: tools/schemacode
        args: ["--settings-file", "tools/schemacode/pyproject.toml"]
  - repo: https://github.com/pyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--config=tools/schemacode/setup.cfg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        entry: env PRETTIER_LEGACY_CLI=1 prettier # temporary fix for https://github.com/prettier/prettier/issues/15742
        files: src/schema/.*/.*\.yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ["--config=.codespellrc", "--dictionary=-", "--dictionary=.codespell_dict"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        # Sync with project.optional-dependencies.typing
        additional_dependencies:
          - click
          - markdown-it-py
          - importlib_resources
          - pandas-stubs
          - pyparsing
          - pytest
          - types-PyYAML
          - types-tabulate
        args: ["tools/schemacode/bidsschematools"]
        pass_filenames: false
