# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: 'tools/schemacode/bidsschematools/tests/data/broken_dataset_description.json'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: check-added-large-files
      - id: check-case-conflict
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        files: tools/schemacode
        args: [--verbose]
  - repo: https://github.com/pyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: tools/
  - repo: https://github.com/pyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--config=tools/schemacode/setup.cfg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.2
    hooks:
      - id: prettier
        files: src/schema/.*/.*\.yaml
